name: Build pipeline

permissions:
  actions: read

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.sh'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.sh'

env:
  DISTRIBUTION: temurin
  JAVA_VERSION: 25

jobs:
  lint-workflow:
    # Run always
    name: Lint Github Workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Actionlint
        # reviewdog/action-actionlint v.1.72.0
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d
        with:
          reporter: github-check
          github_token: ${{ secrets.GITHUB_TOKEN }}

  gradle-build-and-test:
    # Run always
    name: Gradle Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: lint-workflow
    outputs:
      build-artifact-name: gradle-artifacts
      server-version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Java
        # actions/setup-java@v5.2.0
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Run Gradle check
        run: ./gradlew build -x test
      # Archive the build directory (reports, classes, etc.)
      - name: Upload Gradle build artifacts
        # actions/upload-artifact@v7.0.1
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: gradle-artifacts
          path: build/
      - name: Get version
        id: get_version
        run: echo "VERSION=$(./gradlew -q printVersion)" >> "$GITHUB_OUTPUT"

  sonar-analysis:
    # Run on PR and merge to main
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    name: SonarCloud Analysis
    needs: [ gradle-build-and-test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - name: Set up Java
        # actions/setup-java@v5.2.0
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Download Gradle build artifacts
        # actions/download-artifact@v8.0.1
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: ${{ needs.gradle-build-and-test.outputs.build-artifact-name }}
          path: build/
      # Run Sonar analysis, skipping the build step to reuse existing artifacts
      - name: Run SonarCloud analysis
        run: ./gradlew sonar -x compileJava -x test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  scan-repo:
    # Run on PR and merge to main
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    name: Scan repository
    needs: [ sonar-analysis ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      security-events: write
    steps:
      - name: Checkout repository
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Scan repository for vulnerabilities with Trivy
        # aquasecurity/trivy-action v0.36.0
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: rootfs
          scan-ref: "."
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL
          exit-code: 1
      - name: Upload Trivy scan results to GitHub Security tab
        if: github.ref == 'refs/heads/main'
        # github/codeql-action/upload-sarif@v2.25.4
        uses: github/codeql-action/upload-sarif@bc0b696b4103f5fe60f15749af68a046868d511a
        with:
          sarif_file: trivy-results.sarif

  create-release:
    # Run on merge to main
    if: github.ref == 'refs/heads/main'
    name: Create GitHub Release
    needs: [ gradle-build-and-test, scan-repo ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set Release Tag
        id: tag_variable
        run: |
          VERSION="${{ needs.gradle-build-and-test.outputs.server-version }}"
          TAG_NAME="v$VERSION"
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"
      - name: Download Build Artifact
        # actions/download-artifact@v8.0.1
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: ${{ needs.gradle-build-and-test.outputs.build-artifact-name }}
          path: build/
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_variable.outputs.TAG_NAME }}
          name: Release ${{ steps.tag_variable.outputs.TAG_NAME }}
          body: See [RELEASE-NOTES.md](RELEASE-NOTES.md)
          draft: false
          prerelease: false
          files: build/libs/*-all.jar
